# Generated by Django 3.2.3 on 2021-06-16 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_article_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='slug',
        ),
    ]
