# Generated by Django 3.2.3 on 2021-06-16 17:35

import django.contrib.auth.base_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_article_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(default=django.contrib.auth.base_user.AbstractBaseUser.get_username, max_length=25),
        ),
    ]
