# Generated by Django 3.2.3 on 2021-06-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
